name: Poliferie.io
description: Front end for the Poliferie.io platform.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.3+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # BLoC state management.
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0

  # Equatable for item comparisons.
  equatable: ^1.0.2

  # Client to make Http requests.
  http: ^0.12.0+4

  # Show web pages.
  url_launcher: ^5.4.1

  # Percent indicator
  percent_indicator: "^2.1.1"

  # Show rich text from server with markdown
  flutter_markdown: ^0.3.5

  # Adapt text size to container
  auto_size_text: ^2.1.0

  # Small persistence data
  shared_preferences: ^0.5.7+2

  # Dots indicator
  dots_indicator: ^1.1.0

  # Firebase core
  firebase_core: "0.5.0"
  #firebase_core: ^0.4.0+9

  #firebase_analytics: ^5.0.2

  # Cloud Firestore
  cloud_firestore: ^0.14.0+2
  #cloud_firestore: ^0.12.9+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # App icons.
  flutter_launcher_icons: "^0.8.1"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets timport 'package:simple_progress_bar/progress_bar.dart';o your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/mockup/
    - assets/data/
    - assets/data/mockup/
    - assets/data/mockup/users/
    - assets/data/mockup/items/
    - assets/data/mockup/articles/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900

# Flutter App Icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-launcher.png"
  image_path_ios: "assets/images/logo-launcher_ios.png"
